"""Optional driver-level timing statistics.

When ``enable_timing=True`` is passed to :func:`pycubrid.connect` (or
the ``PYCUBRID_ENABLE_TIMING`` environment variable is set), a
:class:`TimingStats` instance is attached to the connection and records
nanosecond-precision elapsed times for connect, execute, fetch, and
close operations.

Usage::

    conn = pycubrid.connect(host="localhost", database="demodb", enable_timing=True)
    # ... run queries ...
    stats = conn.timing_stats
    print(stats)           # human-readable summary
    print(stats.execute_count)
    stats.reset()          # clear accumulated data
"""

from __future__ import annotations

import threading


class TimingStats:
    """Accumulates nanosecond timing data for driver operations.

    All public counters use ``int`` nanoseconds recorded via
    :func:`time.perf_counter_ns`.  A :class:`threading.Lock` serialises
    updates so the object is safe to share across threads that use the
    same connection.

    This class is intentionally **not** a dataclass because
    :class:`threading.Lock` is not picklable and would complicate the
    default ``__init__``/``__repr__`` generated by ``@dataclass``.
    """

    __slots__ = (
        "connect_total_ns",
        "connect_count",
        "execute_total_ns",
        "execute_count",
        "fetch_total_ns",
        "fetch_count",
        "close_total_ns",
        "close_count",
        "_lock",
    )

    def __init__(self) -> None:
        self.connect_total_ns: int = 0
        self.connect_count: int = 0
        self.execute_total_ns: int = 0
        self.execute_count: int = 0
        self.fetch_total_ns: int = 0
        self.fetch_count: int = 0
        self.close_total_ns: int = 0
        self.close_count: int = 0
        self._lock = threading.Lock()

    def record_connect(self, elapsed_ns: int) -> None:
        """Record a connect operation timing."""
        with self._lock:
            self.connect_total_ns += elapsed_ns
            self.connect_count += 1

    def record_execute(self, elapsed_ns: int) -> None:
        """Record an execute operation timing."""
        with self._lock:
            self.execute_total_ns += elapsed_ns
            self.execute_count += 1

    def record_fetch(self, elapsed_ns: int) -> None:
        """Record a fetch operation timing."""
        with self._lock:
            self.fetch_total_ns += elapsed_ns
            self.fetch_count += 1

    def record_close(self, elapsed_ns: int) -> None:
        """Record a close operation timing."""
        with self._lock:
            self.close_total_ns += elapsed_ns
            self.close_count += 1

    def reset(self) -> None:
        """Reset all counters to zero."""
        with self._lock:
            self.connect_total_ns = 0
            self.connect_count = 0
            self.execute_total_ns = 0
            self.execute_count = 0
            self.fetch_total_ns = 0
            self.fetch_count = 0
            self.close_total_ns = 0
            self.close_count = 0

    @staticmethod
    def _fmt_ns(total_ns: int, count: int) -> str:
        """Format nanosecond total as a human-friendly string."""
        if count == 0:
            return "0 calls"
        ms = total_ns / 1_000_000
        avg_ms = ms / count
        return f"{count} calls, {ms:.3f}ms total, {avg_ms:.3f}ms avg"

    def __repr__(self) -> str:
        with self._lock:
            return (
                f"TimingStats("
                f"connect={self._fmt_ns(self.connect_total_ns, self.connect_count)}, "
                f"execute={self._fmt_ns(self.execute_total_ns, self.execute_count)}, "
                f"fetch={self._fmt_ns(self.fetch_total_ns, self.fetch_count)}, "
                f"close={self._fmt_ns(self.close_total_ns, self.close_count)})"
            )
