"""Property-based tests for pycubrid.packet — binary serialization round-trips.

These tests use Hypothesis to verify that PacketWriter → PacketReader round-trips
preserve values exactly, and that parse methods raise on truncated data.

This directly addresses the "mock-bypass" problem (issues #186, #188): by feeding
property-generated bytes through the REAL PacketReader/Writer (not mocks), we catch
serialization bugs that mock-based tests cannot see.

Hypothesis settings:
    - max_examples=200: balances coverage vs CI runtime
    - deadline=None: avoids CI timeouts on slow runners
"""

from __future__ import annotations

import struct
import sys

import pytest
from hypothesis import HealthCheck, given, settings, strategies as st

from pycubrid.constants import DataSize
from pycubrid.packet import PacketReader, PacketWriter


# ---------------------------------------------------------------------------
# Strategies — generate well-typed values for each primitive
# ---------------------------------------------------------------------------

# Shorts are signed 16-bit: range [-32768, 32767]
shorts = st.integers(min_value=-(2**15), max_value=2**15 - 1)

# Ints are signed 32-bit: range [-2147483648, 2147483647]
ints = st.integers(min_value=-(2**31), max_value=2**31 - 1)

# Longs are signed 64-bit
longs = st.integers(min_value=-(2**63), max_value=2**63 - 1)

# Bytes are unsigned 8-bit
bytes_vals = st.integers(min_value=0, max_value=255)
# Floats: use float32 width to verify 32-bit round-trip
floats = st.floats(allow_nan=False, allow_infinity=False, width=32)

# Doubles: full IEEE 754 double range
doubles = st.floats(
    allow_nan=False,
    allow_infinity=False,
    width=64,
)

# Byte strings of reasonable length
byte_strings = st.binary(min_size=0, max_size=256)

# Unicode strings (exclude surrogates which can't encode to UTF-8)
text_strings = st.text(
    alphabet=st.characters(blacklist_categories=("Cs",), blacklist_characters="\x00"),
    min_size=0,
    max_size=100,
)


# ---------------------------------------------------------------------------
# Round-trip property tests — PacketWriter write → PacketReader read
# ---------------------------------------------------------------------------


class TestRoundTripProperties:
    """Verify that writer → reader round-trips preserve values exactly."""

    @given(value=bytes_vals)
    @settings(max_examples=200, deadline=None, suppress_health_check=[HealthCheck.too_slow])
    def test_byte_round_trip(self, value: int) -> None:
        """_write_byte → _parse_byte preserves the value."""
        writer = PacketWriter(reserve_header=False)
        writer._write_byte(value)
        reader = PacketReader(writer.to_bytes())
        assert reader._parse_byte() == value

    @given(value=shorts)
    @settings(max_examples=200, deadline=None, suppress_health_check=[HealthCheck.too_slow])
    def test_short_round_trip(self, value: int) -> None:
        """_write_short → _parse_short preserves the value."""
        writer = PacketWriter(reserve_header=False)
        writer._write_short(value)
        reader = PacketReader(writer.to_bytes())
        assert reader._parse_short() == value

    @given(value=ints)
    @settings(max_examples=200, deadline=None, suppress_health_check=[HealthCheck.too_slow])
    def test_int_round_trip(self, value: int) -> None:
        """_write_int → _parse_int preserves the value."""
        writer = PacketWriter(reserve_header=False)
        writer._write_int(value)
        reader = PacketReader(writer.to_bytes())
        assert reader._parse_int() == value

    @given(value=longs)
    @settings(max_examples=200, deadline=None, suppress_health_check=[HealthCheck.too_slow])
    def test_long_round_trip(self, value: int) -> None:
        """_write_long → _parse_long preserves the value."""
        writer = PacketWriter(reserve_header=False)
        writer._write_long(value)
        reader = PacketReader(writer.to_bytes())
        assert reader._parse_long() == value

    @given(value=floats)
    @settings(max_examples=200, deadline=None, suppress_health_check=[HealthCheck.too_slow])
    def test_float_round_trip(self, value: float) -> None:
        """_write_float → _parse_float preserves the value (32-bit precision)."""
        writer = PacketWriter(reserve_header=False)
        writer._write_float(value)
        reader = PacketReader(writer.to_bytes())
        result = reader._parse_float()
        # Float32 round-trip may have tiny precision loss; use struct to compare.
        assert struct.pack(">f", result) == struct.pack(">f", value)

    @given(value=doubles)
    @settings(max_examples=200, deadline=None, suppress_health_check=[HealthCheck.too_slow])
    def test_double_round_trip(self, value: float) -> None:
        """_write_double → _parse_double preserves the value exactly."""
        writer = PacketWriter(reserve_header=False)
        writer._write_double(value)
        reader = PacketReader(writer.to_bytes())
        assert reader._parse_double() == value

    @given(text=text_strings)
    @settings(max_examples=200, deadline=None, suppress_health_check=[HealthCheck.too_slow])
    def test_null_terminated_string_round_trip(self, text: str) -> None:
        """Null-terminated string encoding/decoding preserves text.

        The writer encodes as UTF-8 + NUL byte. The reader must decode back to
        the original Python string. Surrogates and NUL are excluded by the strategy.

        Note: _write_null_terminated_string writes [4-byte length prefix] + [UTF-8 bytes] + [NUL].
        _parse_null_terminated_string reads [length] bytes from the current offset.
        So the reader must first skip the length prefix (or it reads the wrong bytes).
        """
        writer = PacketWriter(reserve_header=False)
        writer._write_null_terminated_string(text)
        encoded = text.encode("utf-8")
        encoded_len = len(encoded) + 1  # +1 for the NUL terminator
        reader = PacketReader(writer.to_bytes())
        # Skip the 4-byte length prefix that the writer emits
        _ = reader._parse_int()
        assert reader._parse_null_terminated_string(encoded_len) == text

    @given(
        values=st.lists(
            st.tuples(st.integers(min_value=0, max_value=2**31 - 1)),
            min_size=0,
            max_size=20,
        )
    )
    @settings(max_examples=50, deadline=None, suppress_health_check=[HealthCheck.too_slow])
    def test_sequential_int_round_trip(self, values: list[tuple[int]]) -> None:
        """Multiple sequential int writes can be read back in order."""
        writer = PacketWriter(reserve_header=False)
        for (v,) in values:
            writer._write_int(v)
        reader = PacketReader(writer.to_bytes())
        for (v,) in values:
            assert reader._parse_int() == v
        assert reader.bytes_remaining() == 0


# ---------------------------------------------------------------------------
# Truncation property tests — parse methods must raise on insufficient data
# ---------------------------------------------------------------------------


class TestTruncationProperties:
    """Verify that parse methods raise struct.error (or IndexError) on truncated data.

    This is the property-test equivalent of the malformed-response catch path in
    ``_send_and_receive``. If a parse method silently returned wrong data instead
    of raising, the caller would not know to wrap it in OperationalError.
    """

    @given(shortfall=st.integers(min_value=0, max_value=3))
    @settings(max_examples=50, deadline=None)
    def test_parse_int_truncated_raises(self, shortfall: int) -> None:
        """_parse_int on < 4 bytes raises struct.error."""
        available = DataSize.INT - 1 - shortfall
        data = b"\x00" * max(available, 0)
        if len(data) == 0:
            # Empty buffer: struct.unpack_from raises struct.error too
            data = b""
        reader = PacketReader(data)
        with pytest.raises((struct.error, IndexError)):
            reader._parse_int()

    @given(shortfall=st.integers(min_value=0, max_value=2))
    @settings(max_examples=50, deadline=None)
    def test_parse_short_truncated_raises(self, shortfall: int) -> None:
        """_parse_short on < 2 bytes raises struct.error."""
        available = DataSize.SHORT - 1 - shortfall
        data = b"\x00" * max(available, 0)
        reader = PacketReader(data)
        with pytest.raises((struct.error, IndexError)):
            reader._parse_short()

    @given(shortfall=st.integers(min_value=0, max_value=7))
    @settings(max_examples=50, deadline=None)
    def test_parse_long_truncated_raises(self, shortfall: int) -> None:
        """_parse_long on < 8 bytes raises struct.error."""
        available = DataSize.LONG - 1 - shortfall
        data = b"\x00" * max(available, 0)
        reader = PacketReader(data)
        with pytest.raises((struct.error, IndexError)):
            reader._parse_long()

    @given(shortfall=st.integers(min_value=0, max_value=3))
    @settings(max_examples=50, deadline=None)
    def test_parse_float_truncated_raises(self, shortfall: int) -> None:
        """_parse_float on < 4 bytes raises struct.error."""
        available = DataSize.FLOAT - 1 - shortfall
        data = b"\x00" * max(available, 0)
        reader = PacketReader(data)
        with pytest.raises((struct.error, IndexError)):
            reader._parse_float()

    @given(shortfall=st.integers(min_value=0, max_value=7))
    @settings(max_examples=50, deadline=None)
    def test_parse_double_truncated_raises(self, shortfall: int) -> None:
        """_parse_double on < 8 bytes raises struct.error."""
        available = DataSize.DOUBLE - 1 - shortfall
        data = b"\x00" * max(available, 0)
        reader = PacketReader(data)
        with pytest.raises((struct.error, IndexError)):
            reader._parse_double()

    def test_parse_byte_on_empty_raises(self) -> None:
        """_parse_byte on empty buffer raises IndexError (memoryview bounds)."""
        reader = PacketReader(b"")
        with pytest.raises(IndexError):
            reader._parse_byte()


# ---------------------------------------------------------------------------
# Offset consistency property — sequential parsing maintains correct offset
# ---------------------------------------------------------------------------


class TestOffsetConsistency:
    """Verify that bytes_remaining() tracks the offset correctly."""

    @given(n_ints=st.integers(min_value=1, max_value=10))
    @settings(max_examples=100, deadline=None)
    def test_bytes_remaining_after_ints(self, n_ints: int) -> None:
        """After parsing N ints, bytes_remaining = total - N * 4."""
        writer = PacketWriter(reserve_header=False)
        for _ in range(n_ints):
            writer._write_int(0)
        reader = PacketReader(writer.to_bytes())
        total = len(writer.to_bytes())
        assert reader.bytes_remaining() == total
        for i in range(n_ints):
            reader._parse_int()
            assert reader.bytes_remaining() == total - (i + 1) * DataSize.INT
        assert reader.bytes_remaining() == 0

    @given(
        n_bytes=st.integers(min_value=0, max_value=100),
        n_ints=st.integers(min_value=0, max_value=10),
    )
    @settings(max_examples=100, deadline=None)
    def test_mixed_parse_offset_tracking(self, n_bytes: int, n_ints: int) -> None:
        """Mixing _parse_bytes and _parse_int keeps offset correct."""
        writer = PacketWriter(reserve_header=False)
        writer._write_bytes(b"\x00" * n_bytes)
        for _ in range(n_ints):
            writer._write_int(0)
        reader = PacketReader(writer.to_bytes())
        total = n_bytes + n_ints * DataSize.INT
        assert reader.bytes_remaining() == total
        if n_bytes > 0:
            reader._parse_bytes(n_bytes)
        for _ in range(n_ints):
            reader._parse_int()
        assert reader.bytes_remaining() == 0


if __name__ == "__main__":
    sys.exit(pytest.main([__file__, "-v"]))
