#!/usr/bin/env python3
"""Validate official-behavior claims and their differential evidence (#446).

``tests/fixtures/official_differential_claims.json`` lists the official public
behavior pycubrid claims to match, or deliberately deviates from, each tied to
official API inventory ids (#436), upstream scenario ids (#437) and a live case
in ``tests/test_official_differential.py``.

Default mode (offline, every PR): structural checks. The ledger must be
non-empty; ids unique; classification ``match`` or ``deviation`` (a deviation
needs a reason, an issue and pinned ``expected`` observations); every inventory
and scenario id must exist (an empty scenario list needs a ``scenario_gap``);
every claim must have exactly one case and every case one claim; the oracle
pins must equal ``scripts/build_official_oracle.py``; and the generated summary
blocks in the compatibility guides must be current.

``--write-docs`` regenerates those summary blocks from the ledger.

``--evidence FILE`` (required CI lane): validates the JSON Lines evidence the
differential writes. Zero cases, a missing driver identity, a server from
``required_servers`` without a run, a claim without a result on every required
server (an unexplained skip) and any mismatch or unclassified divergence fail.
Agreement is recomputed from the recorded observations and the ledger, so a
record's own ``outcome`` label cannot certify a divergence.
``--json-out``/``--summary-out`` write the evidence summary and a Markdown
table (e.g. ``$GITHUB_STEP_SUMMARY``) whose counts come from the ledger and the
evidence, never from hand-written numbers.
"""

from __future__ import annotations

import argparse
import ast
import csv
import json
import re
import sys
from collections import Counter
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
CLAIMS = ROOT / "tests" / "fixtures" / "official_differential_claims.json"
INVENTORY = ROOT / "tests" / "fixtures" / "official_api_inventory.json"
SCENARIOS = ROOT / "tests" / "fixtures" / "upstream_scenarios.csv"
CASES_MODULE = ROOT / "tests" / "test_official_differential.py"
BUILD_SCRIPT = ROOT / "scripts" / "build_official_oracle.py"
DOCS = {
    "en": ROOT / "docs" / "UPSTREAM_COMPATIBILITY.md",
    "ko": ROOT / "docs" / "ko" / "UPSTREAM_COMPATIBILITY.md",
}
START = "<!-- official-differential-summary:start (generated by scripts/check_official_differential.py --write-docs) -->"
END = "<!-- official-differential-summary:end -->"
CLASSIFICATIONS = ("match", "deviation")
SURFACES = ("wrapper", "native")
ID_PATTERN = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
ISSUE_PATTERN = re.compile(r"^#[1-9][0-9]*$")
LABELS = {
    "en": {
        "surface": "Surface",
        "match": "Match",
        "deviation": "Classified deviation",
        "total": "Total",
        "wrapper": "Wrapper (`CUBRIDdb`)",
        "native": "Native (`_cubrid`)",
        "oracle": "Oracle",
        "servers": "Required servers",
        "deviations": "Classified deviations",
    },
    "ko": {
        "surface": "표면",
        "match": "일치",
        "deviation": "분류된 차이",
        "total": "합계",
        "wrapper": "래퍼 (`CUBRIDdb`)",
        "native": "네이티브 (`_cubrid`)",
        "oracle": "오라클",
        "servers": "필수 서버",
        "deviations": "분류된 차이",
    },
}


def load_claims(path: Path = CLAIMS) -> dict[str, Any]:
    data: dict[str, Any] = json.loads(path.read_text(encoding="utf-8"))
    return data


def inventory_ids(path: Path = INVENTORY) -> set[str]:
    data = json.loads(path.read_text(encoding="utf-8"))
    return {operation["id"] for operation in data["operations"]}


def scenario_ids(path: Path = SCENARIOS) -> set[str]:
    with path.open(encoding="utf-8", newline="") as handle:
        return {row["id"] for row in csv.DictReader(handle)}


def case_ids(path: Path = CASES_MODULE) -> list[str]:
    """Return the literal keys of the module-level ``CASES`` dict."""
    tree = ast.parse(path.read_text(encoding="utf-8"))
    for node in tree.body:
        target = node.target if isinstance(node, ast.AnnAssign) else None
        if isinstance(node, ast.Assign) and len(node.targets) == 1:
            target = node.targets[0]
        value = getattr(node, "value", None)
        if isinstance(target, ast.Name) and target.id == "CASES" and isinstance(value, ast.Dict):
            keys = []
            for key in value.keys:
                if not isinstance(key, ast.Constant) or not isinstance(key.value, str):
                    raise ValueError(f"{path.name}: CASES keys must be string literals")
                keys.append(key.value)
            return keys
    raise ValueError(f"{path.name}: no module-level CASES dict literal")


def build_pins(path: Path = BUILD_SCRIPT) -> dict[str, str]:
    pins: dict[str, str] = {}
    for node in ast.parse(path.read_text(encoding="utf-8")).body:
        if (
            isinstance(node, ast.Assign)
            and len(node.targets) == 1
            and isinstance(node.targets[0], ast.Name)
            and isinstance(node.value, ast.Constant)
            and isinstance(node.value.value, str)
        ):
            pins[node.targets[0].id] = node.value.value
    return pins


def check_claims(
    doc: dict[str, Any],
    *,
    inventory: set[str],
    scenarios: set[str],
    cases: list[str],
    pins: dict[str, str],
) -> list[str]:
    errors: list[str] = []
    oracle = doc.get("oracle", {})
    if oracle.get("cubrid_python_commit") != pins.get("CUBRID_PYTHON_COMMIT"):
        errors.append("oracle.cubrid_python_commit differs from build_official_oracle.py")
    if oracle.get("cci_commit") != pins.get("CCI_COMMIT"):
        errors.append("oracle.cci_commit differs from build_official_oracle.py")
    if not re.fullmatch(r"3\.[0-9]+", str(oracle.get("python", ""))):
        errors.append("oracle.python must be a 3.x version")
    servers = doc.get("required_servers")
    if not isinstance(servers, list) or not servers:
        errors.append("required_servers must be a non-empty list")
    claims = doc.get("claims")
    if not isinstance(claims, list) or not claims:
        return errors + ["the claims ledger has zero claims"]
    seen: set[str] = set()
    for claim in claims:
        cid = str(claim.get("id", ""))
        where = f"claim {cid or '<missing id>'}"
        if not ID_PATTERN.match(cid):
            errors.append(f"{where}: id must be lower-case kebab-case")
        if cid in seen:
            errors.append(f"{where}: duplicate id")
        seen.add(cid)
        if claim.get("surface") not in SURFACES:
            errors.append(f"{where}: surface must be one of {SURFACES}")
        classification = claim.get("classification")
        if classification not in CLASSIFICATIONS:
            errors.append(f"{where}: classification must be one of {CLASSIFICATIONS}")
        if not str(claim.get("summary", "")).strip():
            errors.append(f"{where}: summary is required")
        if not ISSUE_PATTERN.match(str(claim.get("issue", ""))):
            errors.append(f"{where}: issue must look like #123")
        inv = claim.get("inventory_ids")
        if not isinstance(inv, list) or not inv:
            errors.append(f"{where}: at least one inventory id is required")
        else:
            errors.extend(f"{where}: unknown inventory id {i}" for i in inv if i not in inventory)
        scen = claim.get("scenario_ids")
        if not isinstance(scen, list):
            errors.append(f"{where}: scenario_ids must be a list")
        elif not scen and not str(claim.get("scenario_gap", "")).strip():
            errors.append(f"{where}: an empty scenario_ids list needs a scenario_gap reason")
        else:
            errors.extend(f"{where}: unknown scenario id {s}" for s in scen if s not in scenarios)
        expected = claim.get("expected")
        if classification == "deviation":
            if not str(claim.get("reason", "")).strip():
                errors.append(f"{where}: a deviation needs a reason")
            if (
                not isinstance(expected, dict)
                or not str(expected.get("pycubrid", "")).strip()
                or not str(expected.get("native", "")).strip()
            ):
                errors.append(f"{where}: a deviation needs expected pycubrid and native values")
            elif expected["pycubrid"] == expected["native"]:
                errors.append(f"{where}: a deviation's expected values must differ")
        elif classification == "match" and ("expected" in claim or "reason" in claim):
            errors.append(f"{where}: a match claim must not carry deviation expectations")
    counts = Counter(cases)
    errors.extend(f"case {c}: defined more than once" for c, n in counts.items() if n > 1)
    errors.extend(f"claim {c}: no differential case" for c in sorted(seen - set(cases)))
    errors.extend(f"case {c}: no claim in the ledger" for c in sorted(set(cases) - seen))
    return errors


def render_block(doc: dict[str, Any], lang: str) -> str:
    labels = LABELS[lang]
    claims = doc["claims"]
    counts = Counter((c["surface"], c["classification"]) for c in claims)
    lines = [
        START,
        "",
        f"| {labels['surface']} | {labels['match']} | {labels['deviation']} | {labels['total']} |",
        "| --- | ---: | ---: | ---: |",
    ]
    for surface in SURFACES:
        match, deviation = counts[(surface, "match")], counts[(surface, "deviation")]
        lines.append(f"| {labels[surface]} | {match} | {deviation} | {match + deviation} |")
    total_match = sum(counts[(s, "match")] for s in SURFACES)
    total_deviation = sum(counts[(s, "deviation")] for s in SURFACES)
    lines.append(
        f"| **{labels['total']}** | **{total_match}** | **{total_deviation}** | "
        f"**{total_match + total_deviation}** |"
    )
    oracle = doc["oracle"]
    lines += [
        "",
        f"- {labels['oracle']}: cubrid-python `{oracle['cubrid_python_commit'][:12]}`, "
        f"CCI `{oracle['cci_commit'][:12]}`, Python {oracle['python']}",
        f"- {labels['servers']}: " + ", ".join(f"CUBRID {s}" for s in doc["required_servers"]),
        f"- {labels['deviations']}: "
        + ", ".join(
            f"`{c['id']}` ({c['issue']})" for c in claims if c["classification"] == "deviation"
        ),
        "",
        END,
    ]
    return "\n".join(lines)


def _replace_block(text: str, block: str, path: Path) -> str:
    start, end = text.find(START), text.find(END)
    if start < 0 or end < start:
        raise ValueError(f"{path}: generated summary markers are missing")
    return text[:start] + block + text[end + len(END) :]


def check_docs(doc: dict[str, Any], write: bool = False) -> list[str]:
    errors = []
    for lang, path in DOCS.items():
        text = path.read_text(encoding="utf-8")
        updated = _replace_block(text, render_block(doc, lang), path)
        if updated != text:
            if write:
                path.write_text(updated, encoding="utf-8")
            else:
                errors.append(
                    f"{path.relative_to(ROOT)}: summary block is stale; run "
                    "python scripts/check_official_differential.py --write-docs"
                )
    return errors


def _server_matches(version: str, required: str) -> bool:
    return version == required or version.startswith(required + ".")


def check_evidence(doc: dict[str, Any], records: list[dict[str, Any]]) -> dict[str, Any]:
    errors: list[str] = []
    claims = {c["id"]: c for c in doc["claims"]}
    oracle = doc["oracle"]
    environments = [r for r in records if r.get("record") == "environment"]
    cases = [r for r in records if r.get("record") == "case"]
    if not cases:
        errors.append("zero differential cases were recorded")
    for env in environments:
        if not env.get("extension_sha256"):
            errors.append(f"server {env.get('server_version')}: official driver SHA-256 missing")
        for key in ("cubrid_python_commit", "cci_commit"):
            if env.get(key) != oracle[key]:
                errors.append(f"server {env.get('server_version')}: {key}={env.get(key)!r}")
        if not str(env.get("python", "")).startswith(oracle["python"] + "."):
            errors.append(f"server {env.get('server_version')}: Python {env.get('python')}")
    results: dict[str, dict[str, str]] = {}
    for required in doc["required_servers"]:
        if not any(_server_matches(str(e.get("server_version")), required) for e in environments):
            errors.append(f"CUBRID {required}: no official driver run was recorded")
        results[required] = {}
    for case in cases:
        cid = case.get("claim")
        server = str(case.get("server_version"))
        if cid not in claims:
            errors.append(f"{server}: evidence for unknown claim {cid}")
            continue
        claim = claims[cid]
        pycubrid_obs, native_obs = case.get("pycubrid"), case.get("native")
        # Recompute agreement from the observations; never trust the recorded outcome.
        if claim["classification"] == "match":
            agrees = isinstance(native_obs, str) and bool(native_obs) and pycubrid_obs == native_obs
            wanted = "match"
        else:
            expected = claim["expected"]
            agrees = pycubrid_obs == expected["pycubrid"] and native_obs == expected["native"]
            wanted = "classified-deviation"
        if case.get("classification") != claim["classification"]:
            errors.append(
                f"{server} {cid}: recorded classification {case.get('classification')!r} "
                f"differs from the ledger"
            )
        if not agrees:
            errors.append(f"{server} {cid}: mismatch (pycubrid={pycubrid_obs} native={native_obs})")
        elif case.get("outcome") != wanted:
            errors.append(f"{server} {cid}: recorded outcome {case.get('outcome')!r} != {wanted}")
        for required, per_claim in results.items():
            if _server_matches(server, required):
                if cid in per_claim:
                    errors.append(f"{server} {cid}: recorded more than once")
                per_claim[cid] = str(case.get("outcome"))
    for required, per_claim in results.items():
        for cid in claims:
            if cid not in per_claim:
                errors.append(f"CUBRID {required} {cid}: no result (skipped or not run)")
    if errors:
        raise ValueError("\n".join(errors))
    classification_counts = Counter(c["classification"] for c in claims.values())
    return {
        "oracle": oracle,
        "environments": environments,
        "claims": len(claims),
        "classifications": dict(sorted(classification_counts.items())),
        "results": {
            server: dict(sorted(Counter(per.values()).items())) for server, per in results.items()
        },
        "cases": cases,
    }


def summary_markdown(summary: dict[str, Any]) -> str:
    lines = [
        "### Official driver differential evidence",
        "",
        f"{summary['claims']} claims: "
        + ", ".join(f"{n} {k}" for k, n in summary["classifications"].items()),
        "",
        "| Server | Python | Driver SHA-256 | pycubrid | Outcomes |",
        "| --- | --- | --- | --- | --- |",
    ]
    for env in summary["environments"]:
        server = str(env.get("server_version"))
        outcomes = next(
            (
                ", ".join(f"{n} {k}" for k, n in counts.items())
                for required, counts in summary["results"].items()
                if _server_matches(server, required)
            ),
            "",
        )
        lines.append(
            f"| {server} | {env.get('python')} | `{str(env.get('extension_sha256'))[:16]}` | "
            f"`{str(env.get('pycubrid_commit'))[:12]}` | {outcomes} |"
        )
    return "\n".join(lines) + "\n"


def read_records(path: Path) -> list[dict[str, Any]]:
    records = []
    for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if line.strip():
            try:
                records.append(json.loads(line))
            except json.JSONDecodeError as exc:
                raise ValueError(f"{path}:{number}: {exc}") from exc
    return records


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write-docs", action="store_true")
    parser.add_argument("--evidence", type=Path)
    parser.add_argument("--json-out", type=Path)
    parser.add_argument("--summary-out", type=Path)
    args = parser.parse_args(argv)
    try:
        doc = load_claims()
        errors = check_claims(
            doc,
            inventory=inventory_ids(),
            scenarios=scenario_ids(),
            cases=case_ids(),
            pins=build_pins(),
        )
        if not errors:
            errors = check_docs(doc, write=args.write_docs)
        if errors:
            raise ValueError("\n".join(errors))
        if args.evidence is None:
            counts = Counter(c["classification"] for c in doc["claims"])
            print(f"Official differential claims OK: {len(doc['claims'])} ({dict(counts)})")
            return 0
        summary = check_evidence(doc, read_records(args.evidence))
        if args.json_out:
            args.json_out.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
        text = summary_markdown(summary)
        if args.summary_out:
            with args.summary_out.open("a", encoding="utf-8") as handle:
                handle.write(text)
        print(text)
        return 0
    except (ValueError, OSError, KeyError) as exc:
        print(f"Official differential check failed:\n{exc}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
